### ISSUE TITLE
Unclear Which Shells Fit Together

### ISSUE THREAD

**Issue by tshumay** [TheRobotStudio/Dexhand#6]
I'm not sure if there's a matching top/bottom shell set in the STL files. I printed the Forearm_Duplex_Wrist17f_Bulk forearm as my basis, but none of the top shells seem to fit. I started with Forearm_Duplex_Wrist_18i_Split, but there is a gap. And the others seem to not fit  in CAD. 

![Screenshot 2023-06-05 133950](https://github.com/TheRobotStudio/Dexhand/assets/2821763/259f1791-c330-446d-8c5d-ffa5fab6b41b)

**Comment by TheRobotStudio** [comment]
Yes that’s right, the gap allows the cosmetic shells to clip on!On the V2 it’s neater 😁Sent from my iPhoneOn 5 Jun 2023, at 22:43, Trent Shumay ***@***.***> wrote:﻿
I'm not sure if there's a matching top/bottom shell set in the STL files. I printed the Forearm_Duplex_Wrist17f_Bulk forearm as my basis, but none of the top shells seem to fit. I started with Forearm_Duplex_Wrist_18i_Split, but there is a gap. And the others seem to not fit  in CAD.

**Comment by tshumay** [comment]
Ahhh! That makes sense. Thanks! I’ve got the right ones printed then. _____________________________Trenton ShumayCEO, IoT Design Shop Inc. On Jun 5, 2023, at 9:57 PM, TRS ***@***.***> wrote:﻿
Yes that’s right, the gap allows the cosmetic shells to clip on!On the V2 it’s neater 😁Sent from my iPhoneOn 5 Jun 2023, at 22:43, Trent Shumay ***@***.***> wrote:﻿
I'm not sure if there's a matching top/bottom shell set in the STL files. I printed the Forearm_Duplex_Wrist17f_Bulk forearm as my basis, but none of the top shells seem to fit. I started with Forearm_Duplex_Wrist_18i_Split, but there is a gap. And the others seem to not fit  in CAD.
